"""adiciona anticoagulante, materiais, outros_materiais

Revision ID: 021eb47ac1e1
Revises: 
Create Date: 2025-06-14 10:54:08.565781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021eb47ac1e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cirurgia', schema=None) as batch_op:
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('medico',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cirurgia', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('medico',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
